version: "1"
services:
  train:
    image: atorres/train:v1
    build: train/.
    volumes:
      - ./models:/app/models

    command: python -m src.train_model LogisticRegression

  serve:
    build: serve/.
    image: atorres/serve:v1
    ports:
      - 5002:5002
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs/

    command: uvicorn src.predict:app --host 0.0.0.0 --port 5002
